/**
 *
 * $Id$
 */
package CAEX.validation;

import CAEX.NominalScaled;
import CAEX.OrdinalScaled;
import CAEX.UnknownType;

/**
 * A sample validator interface for {@link CAEX.AttributeValueRequirement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValueRequirementValidator {
	boolean validate();

	boolean validateOrdinalScaledType(OrdinalScaled value);
	boolean validateNominalScaledType(NominalScaled value);
	boolean validateUnknownType(UnknownType value);
	boolean validateName(String value);
}
