/**
 *
 * $Id$
 */
package CAEX.validation;

import CAEX.ExternalReference;
import CAEX.InstanceHierarchy;
import CAEX.InterfaceClassLib;
import CAEX.RoleClassLib;
import CAEX.SystemUnitClassLib;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link CAEX.CAEXFile}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CAEXFileValidator {
	boolean validate();

	boolean validateExternalReference(EList<ExternalReference> value);
	boolean validateInstanceHierarchy(EList<InstanceHierarchy> value);
	boolean validateInterfaceClassLib(EList<InterfaceClassLib> value);
	boolean validateRoleClassLib(EList<RoleClassLib> value);
	boolean validateSystemUnitClassLib(EList<SystemUnitClassLib> value);
	boolean validateFileName(String value);
	boolean validateSchemaVersion(String value);
}
