/**
 *
 * $Id$
 */
package CAEX.validation;

import CAEX.Mapping;
import CAEX.RoleRequirements;
import CAEX.SystemUnitClass;

/**
 * A sample validator interface for {@link CAEX.InternalElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InternalElementValidator {
	boolean validate();

	boolean validateRoleRequirements(RoleRequirements value);
	boolean validateMappingObject(Mapping value);
	boolean validateRefBaseSystemUnitPath(String value);

	boolean validateBaseSystemUnit(SystemUnitClass value);
}
