/**
 *
 * $Id$
 */
package CAEX.validation;

import CAEX.AttributeNameMapping;
import CAEX.InterfaceNameMapping;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link CAEX.Mapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappingValidator {
	boolean validate();

	boolean validateAttributeNameMapping(EList<AttributeNameMapping> value);
	boolean validateInterfaceNameMapping(EList<InterfaceNameMapping> value);
}
