/**
 *
 * $Id$
 */
package CAEX.validation;


/**
 * A sample validator interface for {@link CAEX.OrdinalScaled}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OrdinalScaledValidator {
	boolean validate();

	boolean validateRequiredMaxValue(String value);
	boolean validateRequiredValue(String value);
	boolean validateRequiredMinValue(String value);
}
