/**
 *
 * $Id$
 */
package CAEX.validation;

import javax.xml.datatype.XMLGregorianCalendar;

/**
 * A sample validator interface for {@link CAEX.Revision}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RevisionValidator {
	boolean validate();

	boolean validateRevisionDate(XMLGregorianCalendar value);
	boolean validateOldVersion(String value);
	boolean validateNewVersion(String value);
	boolean validateAuthorName(String value);
	boolean validateComment(String value);
}
