/**
 *
 * $Id$
 */
package CAEX.validation;

import CAEX.Mapping;
import CAEX.RoleClass;

/**
 * A sample validator interface for {@link CAEX.SupportedRoleClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SupportedRoleClassValidator {
	boolean validate();

	boolean validateMappingObject(Mapping value);
	boolean validateRefRoleClassPath(String value);

	boolean validateRoleClass(RoleClass value);
}
